### ISSUE TITLE
Let users know how many bullets were in the gun when emptying the gun

### ISSUE THREAD

**Issue by MaikoKingma** [Agadar/DankTimesBot-Plugin-Russian-Roulette#4]
When emptying the gun you would like to know how stupid or smart you were. Eg when you empty the gun and 6 bullets come out you were smart. when only one bullet comes out it was stupid.

**Comment by Agadar** [comment]
Added in 5a695f66ab73db172f1d07254ced004638cc1b2a.

**Comment by Agadar** [comment]
Added in c6ad2ad10b35e7125f50f78e01c60c5f646307a3.
